root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/rankedge"
  cmd = "swag fmt && swag init -g **/**/*.go && go build -o ./tmp/rankedge ./cmd/main.go"
  delay = 1000  
  exclude_dir = ["tmp","docs"]
  exclude_file = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go","mod","sum","env","toml"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false


